### PR TITLE
Export symbols on Windows

### PR DESCRIPTION
**Pull request by metab0t**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks! Did you verified if this work as expected?

**Comment by metab0t** [comment]
Do you know how to download the artifacts of CI to verify it? I test locally and it works.

**Comment by traversaro** [comment]
You can enable the store_build_artifacts option in conda-forge.yml, but if you tested locally that is ok for me, thanks!

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by metab0t** [comment]
In my local machine, MSVC fails at the export names step, so I use clang-cl to build.

However, it seems that MSVC completes the build successfully in CI. The generated `asl.dll` becoimes bigger after exporting symbols.

Should I enable `store_build_artifacts` option to check it?

**Comment by traversaro** [comment]
> In my local machine, MSVC fails at the export names step, so I use clang-cl to build.
> 
> However, it seems that MSVC completes the build successfully in CI. The generated `asl.dll` becoimes bigger after exporting symbols.
> 
> Should I enable `store_build_artifacts` option to check it?

Ah sorry, I merged without waiting. As the package is new and the Windows version was broken anyhow, at this point I think you can directly check the new version as soon as it is built.

**Comment by metab0t** [comment]
I will check it after the new version get updated.

**Comment by metab0t** [comment]
图片

Now `asl.dll` exports these symbols correctly.

**Pull request merged**
